# This file controls the AWS CodeBuild

version: 0.2
phases:
  pre_build:
    commands:
    - echo "Entered the pre-build phase on " `date`
  build:
    commands:
    - echo "Entered build phase on " `date`
    - mvn clean test package
  post_build:
    commands:
    - echo "Entered the post-build phase on " `date`
artifacts:
  files:
    - target/*.jar
  discard-paths: yes